/**
 * Blog posts, read from the `blog` collection and validated before use.
 *
 * Astro already validates the frontmatter shape (see src/content.config.ts).
 * This module adds the checks that need to know *which file* is at fault, plus
 * the derived values the UI wants:
 *
 *   - a URL-safe slug derived from the file name, unique across the collection
 *   - the cover image, resolved from src/assets/blog/ or a loud build failure
 *   - an estimated reading time and a word count
 *   - the author, resolved from src/data/authors.ts
 *   - the YouTube embeds in the body, read back out of the Markdown so the
 *     page's `VideoObject` markup describes the videos that are really there
 *
 * Every failure here throws during `astro build`, so a malformed post cannot
 * reach production. Nothing is fetched from the network: the blog is built
 * entirely from files in this repository.
 */
import type { ImageMetadata } from "astro";
import { getCollection, type CollectionEntry } from "astro:content";

import { slugFromPostPath, tagSegment, tagSlug } from "../lib/post-slug";
import { youtubeEmbedUrl, youtubeWatchUrl } from "../lib/youtube";

import {
  authorById,
  authorSegment,
  authors,
  defaultAuthorId,
  type Author,
} from "./authors";
import { absoluteUrl } from "./site";

export const blogPath = "/blog";
export const blogFeedPath = "/blog/rss.xml";
/**
 * Stable `@id` for the blog as a whole.
 *
 * A post is `isPartOf` this, and the blog index declares the node, so the
 * relationship is stated once here rather than re-described on every post.
 */
export const blogId = `${absoluteUrl(blogPath)}#blog`;
export const blogFeedTitle = "HealThaali — notes and recipes";
/** Tag pages live under /blog/tag/<slug>. */
export const blogTagBase = `${blogPath}/${tagSegment}`;
export const blogTagPath = (slug: string): string => `${blogTagBase}/${slug}`;
/** The URL for a tag as written in frontmatter, e.g. "High protein" → /blog/tag/high-protein. */
export const tagHref = (name: string): string => blogTagPath(tagSlug(name));

export type BlogEntry = CollectionEntry<"blog">;

/**
 * A video embedded in a post body.
 *
 * Read out of the Markdown rather than repeated in frontmatter: two places
 * listing the same video would eventually disagree, and the page's structured
 * data would then describe something the reader cannot see. See `parseVideos`.
 */
export interface BlogVideo {
  /** YouTube id — 11 characters, validated. */
  id: string;
  /** Accessible name: the <iframe> title, the button label and the schema name. */
  title: string;
  /** `vertical` for a Short, `wide` for an ordinary video. */
  shape: "wide" | "vertical";
  /** The video on youtube.com, used by the no-JavaScript fallback link. */
  watchUrl: string;
  /** Privacy-preserving origin used by the player. */
  embedUrl: string;
}

/**
 * Directory segments under /blog that are generated by a page, so a post must
 * not be published there. `/blog/tag/<slug>` comes from post frontmatter and
 * `/blog/author/<id>` from the author list; a post at either address would be
 * written to the same path as a generated page and one would silently win.
 */
const RESERVED_SEGMENTS = [
  { segment: tagSegment, what: "topic pages" },
  { segment: authorSegment, what: "author pages" },
];

export interface BlogTag {
  /** The tag exactly as written in a post's frontmatter. */
  name: string;
  /** Its URL segment, derived by the shared tagSlug(). */
  slug: string;
  href: string;
  /** The posts carrying it, newest first. Never empty. */
  posts: BlogPost[];
}

export interface BlogPost {
  /** URL segment, derived from the file name. `/blog/<slug>`. */
  slug: string;
  href: string;
  title: string;
  description: string;
  publishedAt: Date;
  updatedAt?: Date;
  tags: string[];
  /** Resolved cover image, ready for <Image>. Undefined when the post has none. */
  cover?: ImageMetadata;
  /** Required alongside `cover`; the meaningful description of that image. */
  coverAlt?: string;
  /** Absolute cover URL, for og:image and JSON-LD. */
  coverUrl?: string;
  /** Whole minutes, at 200 words per minute, never below 1. */
  readingMinutes: number;
  /** Words in the body, as the browser measures them (whitespace-separated). */
  wordCount: number;
  /** Who wrote it. Always resolved, so the byline is never blank. */
  author: Author;
  /** YouTube embeds in the body, in the order they appear. */
  videos: BlogVideo[];
  /** The raw entry, so pages can hand it to `render()`. */
  entry: BlogEntry;
}

/**
 * Covers are imported eagerly so Astro's image pipeline processes them and we
 * can read their real dimensions at build time. Adding a new cover means
 * dropping a file in `src/assets/blog/` — no code change.
 */
const coverModules = import.meta.glob<{ default: ImageMetadata }>(
  "../assets/blog/*.{png,jpg,jpeg,webp,avif}",
  { eager: true },
);

const coversByName = new Map<string, ImageMetadata>();
for (const [path, module] of Object.entries(coverModules)) {
  coversByName.set(path.slice(path.lastIndexOf("/") + 1), module.default);
}

const coverFileNames = () => [...coversByName.keys()].sort();

/**
 * Every Markdown file in the content directory, as a path relative to it.
 *
 * This exists because the collection itself cannot be trusted to report a
 * collision: Astro keys entries by id, so two files that reduce to the same
 * slug become one store entry and the later file silently replaces the
 * earlier. By the time `getCollection` runs, the evidence is already gone —
 * one file has simply disappeared, with no warning in the build log. Reading
 * the directory is the only way to see both.
 */
const postFilePaths = Object.keys(import.meta.glob("../content/blog/**/*.{md,mdx}")).map((path) =>
  path.replace(/^.*\/content\/blog\//, ""),
);

const assertPostSlugsAreUsable = (): void => {
  const bySlug = new Map<string, string[]>();

  for (const file of postFilePaths) {
    const slug = slugFromPostPath(file);
    bySlug.set(slug, [...(bySlug.get(slug) ?? []), file]);

    for (const { segment, what } of RESERVED_SEGMENTS) {
      if (slug === segment || slug.startsWith(`${segment}/`)) {
        fail(
          `"${file}" would publish under /blog/${segment}/…, which is where the ${what} ` +
            `live. One would silently overwrite the other depending on build order. ` +
            `Move it out of that directory.`,
        );
      }
    }
  }

  for (const [slug, files] of bySlug) {
    if (files.length > 1) {
      fail(
        `${files.join(" and ")} would all publish at /blog/${slug}. Only one entry ` +
          `per URL survives, so the others would vanish without a warning. Rename them ` +
          `so each resolves to its own slug.`,
      );
    }
  }
};

/**
 * A build failure that names the file at fault.
 *
 * Declared as a function (not an arrow const) so TypeScript treats a call as
 * terminating: after `if (!x) fail(…)` it narrows `x`, which is what lets the
 * checks above hand on a value they have just proved.
 */
function fail(message: string): never {
  throw new Error(`[blog] ${message}`);
}

const wordCount = (body: string | undefined): number =>
  (body ?? "").trim().split(/\s+/).filter(Boolean).length;

/** Whole minutes at 200 words per minute, never below 1. */
const readingTime = (words: number): number => Math.max(1, Math.round(words / 200));

/**
 * The YouTube embeds a post actually contains, read back out of its Markdown.
 *
 * The body is the only place an embed is declared, so there is nothing to keep
 * in sync: whatever the reader can see is what the page's `VideoObject` markup
 * describes. Each `<figure class="yt-embed" …>` is checked here rather than
 * trusted, because every one of these failures produces a *quietly* broken
 * player instead of a build error:
 *
 *   - a malformed id renders a "video unavailable" frame,
 *   - a missing title leaves the <iframe> with no accessible name, which is a
 *     WCAG failure the a11y gate would catch only after the fact,
 *   - a fallback link pointing at a *different* video breaks the page for
 *     someone without JavaScript, and nothing else would ever notice,
 *   - a missing caption drops a video into the prose with no explanation.
 */
const YOUTUBE_ID = /^[A-Za-z0-9_-]{11}$/;
const EMBED_FIGURE = /<figure\b[^>]*class="[^"]*\byt-embed\b[^"]*"[\s\S]*?<\/figure>/g;

const attribute = (markup: string, name: string): string => {
  const match = new RegExp(`${name}="([^"]*)"`).exec(markup);
  return match ? match[1].trim() : "";
};

const parseVideos = (body: string | undefined, slug: string): BlogVideo[] => {
  const figures = (body ?? "").match(EMBED_FIGURE) ?? [];
  const videos: BlogVideo[] = [];
  const seen = new Set<string>();

  for (const figure of figures) {
    const id = attribute(figure, "data-yt");
    const title = attribute(figure, "data-yt-title");
    const shape = attribute(figure, "data-yt-shape") || "wide";

    if (!YOUTUBE_ID.test(id)) {
      fail(
        `"${slug}" embeds a video with data-yt="${id}". A YouTube id is exactly ` +
          `11 characters of A-Z, a-z, 0-9, "-" or "_".`,
      );
    }
    if (title.length === 0) {
      fail(
        `"${slug}" embeds ${id} without data-yt-title. That string is the frame's ` +
          `accessible name, so the video cannot be announced without it.`,
      );
    }
    if (shape !== "wide" && shape !== "vertical") {
      fail(
        `"${slug}" gives ${id} data-yt-shape="${shape}". Use "wide" (16:9) or ` +
          `"vertical" (9:16, for a Short).`,
      );
    }
    if (seen.has(id)) {
      fail(`"${slug}" embeds ${id} more than once. Keep one player per video.`);
    }
    if (!/<figcaption\b[^>]*>\s*\S/.test(figure)) {
      fail(
        `"${slug}" embeds ${id} without a <figcaption>. Say what the video shows ` +
          `and why it is here, or take the embed out.`,
      );
    }

    // Without JavaScript the figure falls back to this link, so it has to point
    // at the video in the frame above it — not merely at youtube.com.
    const fallback = /<a\b[^>]*href="([^"]+)"/.exec(figure)?.[1] ?? "";
    if (!fallback.endsWith(id)) {
      fail(
        `"${slug}" embeds ${id}, but its fallback link points at ` +
          `"${fallback || "nothing"}". The link is what a reader without JavaScript ` +
          `gets, so it must end with the video id.`,
      );
    }

    seen.add(id);
    videos.push({
      id,
      title,
      shape,
      watchUrl: youtubeWatchUrl(id),
      embedUrl: youtubeEmbedUrl(id),
    });
  }

  // A figure the regex did not match would be an embed that renders but is
  // missing from the structured data, so the count is checked rather than
  // assumed.
  const declared = (body ?? "").split(/data-yt=/).length - 1;
  if (declared !== videos.length) {
    fail(
      `"${slug}" has ${declared} data-yt attribute(s) but only ${videos.length} ` +
        `complete embed figure(s). Every embed needs the full <figure ` +
        `class="yt-embed" …> … </figure> block.`,
    );
  }

  return videos;
};

/** The post's author, or the team byline. An unknown id is a build failure. */
const resolveAuthor = (entry: BlogEntry, slug: string): Author => {
  const id = entry.data.author ?? defaultAuthorId;
  const author = authorById(id);

  if (!author) {
    fail(
      `"${slug}" names author "${id}", who is not in src/data/authors.ts. ` +
        `Known authors: ${authors.map((entry) => entry.id).join(", ")}.`,
    );
  }

  return author;
};

/**
 * The post page supplies the <h1> from the frontmatter title, so a `#` heading
 * in the Markdown body would render a second one. No WCAG rule flags a
 * duplicate h1, which means nothing else in this project would catch it, so it
 * is caught here. Fenced code blocks are stripped first, because a `#` comment
 * in a shell snippet is not a heading.
 */
const assertNoH1InBody = (body: string | undefined, slug: string): void => {
  if (!body) return;

  const withoutCode = body
    .replace(/^```[\s\S]*?^```[^\n]*$/gm, "")
    .replace(/^~~~[\s\S]*?^~~~[^\n]*$/gm, "");

  if (/^#\s+\S/m.test(withoutCode)) {
    fail(
      `"${slug}" has a level-1 heading in its body. The title is already the <h1>; ` +
        `start body headings at "##".`,
    );
  }
};

const resolveCover = (entry: BlogEntry, slug: string): ImageMetadata | undefined => {
  const { cover, coverAlt } = entry.data;

  if (cover && !coverAlt) {
    fail(`"${slug}" sets a cover but no coverAlt. Describe the image, or drop the cover.`);
  }

  if (!cover) {
    return undefined;
  }

  const image = coversByName.get(cover);
  if (!image) {
    const available = coverFileNames();
    fail(
      `"${slug}" points at cover "${cover}", which is not in src/assets/blog/.\n` +
        (available.length > 0
          ? `       Available: ${available.join(", ")}`
          : "       That directory has no images yet."),
    );
  }

  return image;
};

/**
 * Published posts, newest first.
 *
 * Drafts are excluded unconditionally. See the note in src/content.config.ts:
 * there is one code path, so a draft cannot leak into a production build.
 */
export async function getPosts(): Promise<BlogPost[]> {
  // Checked before the collection is read: a collision means an entry has
  // already been dropped from it, so this must fail the build first.
  assertPostSlugsAreUsable();

  const entries = await getCollection("blog", ({ data }) => !data.draft);

  const posts = entries.map((entry) => {
    // `entry.id` is the slug: the collection's generateId is the same shared
    // slugFromPostPath that assertNoSlugCollisions just checked the directory
    // with. See src/lib/post-slug.ts.
    const slug = entry.id;

    const { publishedAt, updatedAt } = entry.data;
    if (updatedAt && updatedAt.getTime() < publishedAt.getTime()) {
      fail(`"${slug}" was updated before it was published. Check publishedAt and updatedAt.`);
    }

    assertNoH1InBody(entry.body, slug);

    const cover = resolveCover(entry, slug);
    const words = wordCount(entry.body);

    return {
      slug,
      href: `${blogPath}/${slug}`,
      title: entry.data.title,
      description: entry.data.description,
      publishedAt,
      updatedAt,
      tags: entry.data.tags,
      cover,
      coverAlt: cover ? entry.data.coverAlt : undefined,
      coverUrl: cover ? absoluteUrl(cover.src) : undefined,
      readingMinutes: readingTime(words),
      wordCount: words,
      author: resolveAuthor(entry, slug),
      videos: parseVideos(entry.body, slug),
      entry,
    } satisfies BlogPost;
  });

  return posts.sort((a, b) => b.publishedAt.getTime() - a.publishedAt.getTime());
}

/**
 * Every topic in use, most-used first and then alphabetically.
 *
 * Two things are checked rather than assumed, because both produce a broken
 * site rather than an error:
 *
 *   - a tag with no URL-usable characters ("…", "!!!") would slug to an empty
 *     segment and generate `/blog/tag/` — a duplicate of the blog index.
 *   - two different spellings that reduce to one slug ("High Protein" and
 *     "high-protein") would generate the same page twice, and one would
 *     silently replace the other. Their posts are merged only when the names
 *     match exactly.
 *
 * Only published posts are passed in, so a tag disappears when its last post
 * does. There is no tag registry to keep in sync by hand.
 */
export const collectTags = (posts: BlogPost[]): BlogTag[] => {
  const bySlug = new Map<string, BlogTag>();

  for (const post of posts) {
    // A post may repeat a tag in two spellings; it must still appear once.
    const seenHere = new Set<string>();

    for (const name of post.tags) {
      const slug = tagSlug(name);

      if (slug.length === 0) {
        fail(
          `the tag "${name}" on "${post.slug}" has no characters usable in a URL. ` +
            `Rename the tag, or remove it.`,
        );
      }

      const existing = bySlug.get(slug);

      if (existing) {
        if (existing.name !== name) {
          fail(
            `the tags "${existing.name}" and "${name}" both resolve to ${blogTagPath(slug)}. ` +
              `One page would replace the other — rename one of them.`,
          );
        }
        if (!seenHere.has(slug)) existing.posts.push(post);
      } else {
        bySlug.set(slug, { name, slug, href: blogTagPath(slug), posts: [post] });
      }

      seenHere.add(slug);
    }
  }

  return [...bySlug.values()].sort(
    (a, b) => b.posts.length - a.posts.length || a.name.localeCompare(b.name),
  );
};

/**
 * Up to `limit` other posts that share at least one tag, best match first.
 *
 * Anything with nothing in common is left out rather than padded in: a
 * "related" section that links unrelated posts is worse than no section, so the
 * caller is expected to render nothing when this returns an empty array.
 * `posts` arrives newest-first, which is also the tie-break.
 */
export const relatedPosts = (post: BlogPost, posts: BlogPost[], limit = 3): BlogPost[] => {
  const own = new Set(post.tags.map(tagSlug));
  if (own.size === 0) return [];

  return posts
    .filter((candidate) => candidate.slug !== post.slug)
    .map((candidate) => ({
      candidate,
      shared: candidate.tags.filter((tag) => own.has(tagSlug(tag))).length,
    }))
    .filter((entry) => entry.shared > 0)
    .sort(
      (a, b) =>
        b.shared - a.shared || b.candidate.publishedAt.getTime() - a.candidate.publishedAt.getTime(),
    )
    .slice(0, limit)
    .map((entry) => entry.candidate);
};

/** "12 March 2026" — the same format the recipe dates use. */
export const formatPostDate = (date: Date): string =>
  date.toLocaleDateString("en-GB", {
    day: "numeric",
    month: "long",
    year: "numeric",
    timeZone: "UTC",
  });

/** The `datetime` attribute value for a <time> element. */
export const postDateAttribute = (date: Date): string => date.toISOString().slice(0, 10);
